modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL=""
license="MIT"

[[mods]]
modId="fullfud"
version="${version}"
displayName="Fullfud"
credits=""
authors="fullfud"
description='''
Simple foundation for the Fullfud mod.
'''

[[dependencies.fullfud]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.fullfud]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
