modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL=""
license="See LICENSE file"

[[mods]]
modId="fullfud"
version="${version}"
displayName="Shadedwar"
credits=""
authors="fullfud"
description='''
Realistic UAV, etc.
'''

[[dependencies.fullfud]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.fullfud]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.fullfud]]
modId="geckolib"
mandatory=true
versionRange="[4.3.1,)"
ordering="NONE"
side="BOTH"
