modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/LazuriteMC/Lattice/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://lazurite.dev"
logoFile="assets/lattice/icon.png"
authors="${mod_author}"
description='''
${mod_description}
'''
mixinConfigs="lattice.common.mixins.json,lattice.client.mixins.json"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
